---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-pet
  labels:
    app: petclinic
spec:
  minReadySeconds: 2
  replicas: 4
  selector:
    matchLabels:
      app: spring
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50
      maxUnavailable: 2
  template:
    metadata:
      labels: 
        app: spring
    spec:
      containers:
        - name: springpetclinic
          image: divyak123/jenkinspetclinic:latest
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata: 
  name: petclinic
  labels:
    app: spring
spec:
  selector:
    app: spring
  type: NodePort
  ports:
    - name: http
      nodePort:  31000
      port: 8080
      targetPort: 8080
